ifndef KSU_KBUILD_GUARD
KSU_KBUILD_GUARD := 1


kernelsu-objs := ksu.o
kernelsu-objs += allowlist.o
kernelsu-objs += app_profile.o
kernelsu-objs += apk_sign.o
kernelsu-objs += sucompat.o
kernelsu-objs += syscall_hook_manager.o
kernelsu-objs += throne_tracker.o
kernelsu-objs += pkg_observer.o
kernelsu-objs += setuid_hook.o
kernelsu-objs += kernel_umount.o
kernelsu-objs += supercalls.o
kernelsu-objs += su_mount_ns.o
kernelsu-objs += feature.o
kernelsu-objs += ksud.o
kernelsu-objs += seccomp_cache.o
kernelsu-objs += file_wrapper.o
kernelsu-objs += util.o
kernelsu-objs += extras.o



kernelsu-objs += selinux/selinux.o
kernelsu-objs += selinux/sepolicy.o
kernelsu-objs += selinux/rules.o
ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h
ccflags-y += -I$(srctree)/security/baseband-guard/ -I$(srctree)/security/baseband-guard/tracing


obj-$(CONFIG_KSU) += kernelsu.o

KDIR ?= $(srctree)
MDIR := $(realpath $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))

# Hardcoded version to avoid git shell commands that break in-tree builds
KSU_VERSION := 30001
KSU_VERSION_TAG := v1.0.0-neutrino
$(info -- KernelSU-Next version: $(KSU_VERSION) (hardcoded))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
ccflags-y += -DKSU_VERSION_TAG=\"$(KSU_VERSION_TAG)\"

ifndef KSU_NEXT_MANAGER_SIZE
KSU_NEXT_MANAGER_SIZE := 0x3e6
endif

ifndef KSU_NEXT_MANAGER_HASH
KSU_NEXT_MANAGER_HASH := 79e590113c4c4c0c222978e413a5faa801666957b1212a328e46c00c69821bf7
endif

ifndef KSU_MANAGER_SIZES
KSU_MANAGER_SIZES := $(KSU_NEXT_MANAGER_SIZE),0x35c,0x375,0x396
endif

ifndef KSU_MANAGER_HASHES
KSU_MANAGER_HASHES := "$(KSU_NEXT_MANAGER_HASH)","947ae944f3de4ed4c21a7e4f7953ecf351bfa2b36239da37a34111ad29993eef","484fcba6e6c43b1fb09700633bf2fb4758f13cb0b2f4457b80d075084b26c588","f415f4ed9435427e1fdf7f1fccd4dbc07b3d6b8751e4dbcec6f19671f427870b"
endif

ifdef KSU_MANAGER_PACKAGE
ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
$(info -- KernelSU-Next Manager package name: $(KSU_MANAGER_PACKAGE))
endif

$(info -- KernelSU-Next Manager signature size: $(KSU_NEXT_MANAGER_SIZE))
$(info -- KernelSU-Next Manager signature hash: $(KSU_NEXT_MANAGER_HASH))
$(info -- KernelSU Manager signature sizes: $(KSU_MANAGER_SIZES))
$(info -- KernelSU Manager signature hashes: $(KSU_MANAGER_HASHES))

ccflags-y += -DKSU_MANAGER_SIZES=$(KSU_MANAGER_SIZES)
ccflags-y += -DKSU_MANAGER_HASHES=$(KSU_MANAGER_HASHES)

ccflags-y += -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat -Wno-missing-prototypes
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function -Wno-unused-variable

# Keep a new line here!! Because someone may append config
endif # KSU_KBUILD_GUARD
